### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by jottinger** [artemis-ag/apps-cannapis#15]
I'm trying to run the app clean, because I lost something in how I was configuring it, and now I'm lost in terms of infrastructure again. It's probably a setup thing I'm missing - probably something super-simple - but I'm not seeing it. The output of docker-compose up is attached (was initially run with `docker-compose up --build` as the README specifies.)
[docker-output.txt](https://github.com/artemis-ag/apps-cannapis/files/4231602/docker-output.txt)

**Comment by betacar** [comment]
Hey @jottinger!
Did you set the Postgres credentials on your `.env` file? Please make sure all the following variables have a value.

```env
POSTGRES_DB=
POSTGRES_HOST=
POSTGRES_USER=
POSTGRES_PASSWORD=
```

Rails will use these values to connect to the database.

**Comment by jottinger** [comment]
GAH! Okay, that's one issue - for docker, the POSTGRES_DB needs to be set to `cannapis-db`, and the other values need to be set as well. Next problems:

sidekiq complains with an "invalid uri scheme" of '' but I'm... not sure where the uri is being handed to it, and on hitting the web app, I'm getting this:

Webpacker can't find application in /var/artemis/app/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}

**Comment by jottinger** [comment]
The contents of .env *right now* contain:

```RAILS_ENV=
RAILS_MAX_THREADS=10
POSTGRES_DB=
POSTGRES_HOST=cannapi-db
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
NODE_ENV=
ARTEMIS_BASE_URI=
ARTEMIS_OAUTH_APP_SECRET=
ARTEMIS_OAUTH_APP_ID=
REDIS_ADDRESS=redis://redis/0```

Obviously this isn't complete - I'm going to need to work out the artemis URI and secret (and then start adding modularization again for other modules) but I'm just trying to get everything cranking from first principles.
